from trdg.generators.from_dict import GeneratorFromDict
from trdg.generators.from_random import GeneratorFromRandom
from trdg.generators.from_strings import GeneratorFromStrings
from trdg.generators.from_pictograms import GeneratorFromPictograms
from trdg.generators.from_wikipedia import GeneratorFromWikipedia
